version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/worker'
    schedule:
      interval: 'weekly'
    groups:
      dev-dependencies:
        patterns: ['*']
        update-types: ['minor', 'patch']

    reviewers:
      - "01max"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - "01max"
